services:
  - type: web
    name: stockGame
    env: node
    buildCommand: npm install && NODE_ENV=production npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stockGame-db
          property: connectionString
      - key: NODE_ENV
        value: production 