services:
  - type: web
    name: stockGame
    env: node
    buildCommand: npm install && cd client && npm install --save-dev webpack-cli && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stockGame-db
          property: connectionString
      - key: NODE_ENV
        value: production 